FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04-rc

ENV DEBIAN_FRONTEND=nointeractive
ENV TZ=Asia/Tokyo

# USE MIRROR
RUN sed -i.bak -r 's!(deb|deb-src) \S+!\1 mirror://mirrors.ubuntu.com/mirrors.txt!' /etc/apt/sources.list
RUN curl -SL https://deb.nodesource.com/setup_14.x | bash
RUN apt-get update
RUN apt-get install -y tzdata

# INSTALL NODEJS
RUN apt-get -y install curl dirmngr apt-transport-https lsb-release ca-certificates

# INSTALL JUPYTER PYTHON
RUN apt-get install -y build-essential git wget python3 python3-pip nodejs
RUN python3 -m pip install jupyterlab==3.0.0 && \
    python3 -m pip install jupyterlab-lsp==3.9.1 && \
    python3 -m pip install python-lsp-server && \
    python3 -m pip install nodejs>=12.0.0
RUN python3 -m jupyter labextension install --no-build '@krassowski/jupyterlab-lsp@3.9.1' && \
    python3 -m jupyter lab build --dev-build=False --minimize=True

# INSTALL requirements.txt
ADD requirements.txt /src/
RUN python3 -m pip install -r /src/requirements.txt

# INITIALIZE CONFIGURATION
ADD .user_config /root/.jupyter/user-settings